import {
  AchievementCategory,
  AchievementCriterio,
} from './entities/achievement.entity';

export const achievementsSeed = [
  // ASISTENCIA
  {
    nombre: 'Primera Semana',
    descripcion: 'Asistir al gimnasio 7 días',
    icono: '🎯',
    categoria: AchievementCategory.ASISTENCIA,
    criterio: AchievementCriterio.ASISTIR_7_DIAS,
    objetivo: 7,
    puntos: 10,
    orden: 1,
  },
  {
    nombre: 'Primer Mes',
    descripcion: 'Asistir al gimnasio 30 días',
    icono: '📅',
    categoria: AchievementCategory.ASISTENCIA,
    criterio: AchievementCriterio.ASISTIR_30_DIAS,
    objetivo: 30,
    puntos: 30,
    orden: 2,
  },
  {
    nombre: 'Centurión',
    descripcion: 'Asistir al gimnasio 100 días',
    icono: '💯',
    categoria: AchievementCategory.ASISTENCIA,
    criterio: AchievementCriterio.ASISTIR_100_DIAS,
    objetivo: 100,
    puntos: 100,
    orden: 3,
  },
  {
    nombre: 'Año de Hierro',
    descripcion: 'Asistir al gimnasio 365 días',
    icono: '👑',
    categoria: AchievementCategory.ASISTENCIA,
    criterio: AchievementCriterio.ASISTIR_365_DIAS,
    objetivo: 365,
    puntos: 500,
    orden: 4,
  },
  {
    nombre: 'Racha de Fuego',
    descripcion: 'Asistir 7 días consecutivos',
    icono: '🔥',
    categoria: AchievementCategory.ASISTENCIA,
    criterio: AchievementCriterio.RACHA_7_DIAS,
    objetivo: 7,
    puntos: 20,
    orden: 5,
  },
  {
    nombre: 'Imparable',
    descripcion: 'Asistir 30 días consecutivos',
    icono: '⚡',
    categoria: AchievementCategory.ASISTENCIA,
    criterio: AchievementCriterio.RACHA_30_DIAS,
    objetivo: 30,
    puntos: 50,
    orden: 6,
  },

  // PROGRESO
  {
    nombre: 'Punto de Partida',
    descripcion: 'Registrar tu primer progreso',
    icono: '📊',
    categoria: AchievementCategory.PROGRESO,
    criterio: AchievementCriterio.REGISTRAR_PRIMER_PROGRESO,
    objetivo: 1,
    puntos: 5,
    orden: 7,
  },
  {
    nombre: 'Seguimiento Constante',
    descripcion: 'Registrar 10 progresos',
    icono: '📈',
    categoria: AchievementCategory.PROGRESO,
    criterio: AchievementCriterio.REGISTRAR_10_PROGRESOS,
    objetivo: 10,
    puntos: 20,
    orden: 8,
  },
  {
    nombre: 'Diario de Progreso',
    descripcion: 'Registrar 50 progresos',
    icono: '📝',
    categoria: AchievementCategory.PROGRESO,
    criterio: AchievementCriterio.REGISTRAR_50_PROGRESOS,
    objetivo: 50,
    puntos: 50,
    orden: 9,
  },
  {
    nombre: 'Transformación Ligera',
    descripcion: 'Perder 5 kg de peso',
    icono: '🎈',
    categoria: AchievementCategory.PROGRESO,
    criterio: AchievementCriterio.PERDER_5KG,
    objetivo: 5,
    puntos: 30,
    orden: 10,
  },
  {
    nombre: 'Transformación Mayor',
    descripcion: 'Perder 10 kg de peso',
    icono: '🌟',
    categoria: AchievementCategory.PROGRESO,
    criterio: AchievementCriterio.PERDER_10KG,
    objetivo: 10,
    puntos: 100,
    orden: 11,
  },
  {
    nombre: 'Ganancia Sólida',
    descripcion: 'Ganar 5 kg de peso',
    icono: '💪',
    categoria: AchievementCategory.PROGRESO,
    criterio: AchievementCriterio.GANAR_5KG,
    objetivo: 5,
    puntos: 30,
    orden: 12,
  },
  {
    nombre: 'Construcción Muscular',
    descripcion: 'Ganar 10 kg de peso',
    icono: '🏋️',
    categoria: AchievementCategory.PROGRESO,
    criterio: AchievementCriterio.GANAR_10KG,
    objetivo: 10,
    puntos: 100,
    orden: 13,
  },

  // CLASES
  {
    nombre: 'Vida Social',
    descripcion: 'Reservar tu primera clase',
    icono: '🎉',
    categoria: AchievementCategory.SOCIAL,
    criterio: AchievementCriterio.RESERVAR_PRIMERA_CLASE,
    objetivo: 1,
    puntos: 5,
    orden: 14,
  },
  {
    nombre: 'Clase Regular',
    descripcion: 'Reservar 10 clases',
    icono: '📆',
    categoria: AchievementCategory.SOCIAL,
    criterio: AchievementCriterio.RESERVAR_10_CLASES,
    objetivo: 10,
    puntos: 20,
    orden: 15,
  },
  {
    nombre: 'Fanático de Clases',
    descripcion: 'Reservar 50 clases',
    icono: '🎪',
    categoria: AchievementCategory.SOCIAL,
    criterio: AchievementCriterio.RESERVAR_50_CLASES,
    objetivo: 50,
    puntos: 50,
    orden: 16,
  },
  {
    nombre: 'Participante Activo',
    descripcion: 'Asistir a 10 clases',
    icono: '✅',
    categoria: AchievementCategory.SOCIAL,
    criterio: AchievementCriterio.ASISTIR_10_CLASES,
    objetivo: 10,
    puntos: 30,
    orden: 17,
  },
  {
    nombre: 'Maestro de Clases',
    descripcion: 'Asistir a 50 clases',
    icono: '🏆',
    categoria: AchievementCategory.SOCIAL,
    criterio: AchievementCriterio.ASISTIR_50_CLASES,
    objetivo: 50,
    puntos: 100,
    orden: 18,
  },
];
