/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as SubscriptionsIndexRouteImport } from './routes/subscriptions.index'
import { Route as RoutinesIndexRouteImport } from './routes/routines.index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as WorkoutsPrsRouteImport } from './routes/workouts.prs'
import { Route as WorkoutsNewRouteImport } from './routes/workouts.new'
import { Route as TrainerDashboardRouteImport } from './routes/trainer.dashboard'
import { Route as TrainerClientsRouteImport } from './routes/trainer.clients'
import { Route as RoutinesLogsRouteImport } from './routes/routines.logs'
import { Route as RoutinesRoutineIdRouteImport } from './routes/routines.$routineId'
import { Route as TrainerClientsIndexRouteImport } from './routes/trainer.clients.index'
import { Route as TrainerClientsClientIdRouteImport } from './routes/trainer.clients.$clientId'
import { Route as ExercisesExerciseIdHistoryRouteImport } from './routes/exercises.$exerciseId.history'

const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsIndexRoute = SubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsPrsRoute = WorkoutsPrsRouteImport.update({
  id: '/workouts/prs',
  path: '/workouts/prs',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/workouts/new',
  path: '/workouts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerDashboardRoute = TrainerDashboardRouteImport.update({
  id: '/trainer/dashboard',
  path: '/trainer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerClientsRoute = TrainerClientsRouteImport.update({
  id: '/trainer/clients',
  path: '/trainer/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesLogsRoute = RoutinesLogsRouteImport.update({
  id: '/routines/logs',
  path: '/routines/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoutineIdRoute = RoutinesRoutineIdRouteImport.update({
  id: '/routines/$routineId',
  path: '/routines/$routineId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerClientsIndexRoute = TrainerClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerClientsRoute,
} as any)
const TrainerClientsClientIdRoute = TrainerClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => TrainerClientsRoute,
} as any)
const ExercisesExerciseIdHistoryRoute =
  ExercisesExerciseIdHistoryRouteImport.update({
    id: '/exercises/$exerciseId/history',
    path: '/exercises/$exerciseId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/routines/logs': typeof RoutinesLogsRoute
  '/trainer/clients': typeof TrainerClientsRouteWithChildren
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/prs': typeof WorkoutsPrsRoute
  '/exercises': typeof ExercisesIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/exercises/$exerciseId/history': typeof ExercisesExerciseIdHistoryRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRoute
  '/trainer/clients/': typeof TrainerClientsIndexRoute
}
export interface FileRoutesByTo {
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/routines/logs': typeof RoutinesLogsRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/prs': typeof WorkoutsPrsRoute
  '/exercises': typeof ExercisesIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/subscriptions': typeof SubscriptionsIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/exercises/$exerciseId/history': typeof ExercisesExerciseIdHistoryRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRoute
  '/trainer/clients': typeof TrainerClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/routines/$routineId': typeof RoutinesRoutineIdRoute
  '/routines/logs': typeof RoutinesLogsRoute
  '/trainer/clients': typeof TrainerClientsRouteWithChildren
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/prs': typeof WorkoutsPrsRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/subscriptions/': typeof SubscriptionsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/exercises/$exerciseId/history': typeof ExercisesExerciseIdHistoryRoute
  '/trainer/clients/$clientId': typeof TrainerClientsClientIdRoute
  '/trainer/clients/': typeof TrainerClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/routines/$routineId'
    | '/routines/logs'
    | '/trainer/clients'
    | '/trainer/dashboard'
    | '/workouts/new'
    | '/workouts/prs'
    | '/exercises'
    | '/routines'
    | '/subscriptions'
    | '/workouts'
    | '/exercises/$exerciseId/history'
    | '/trainer/clients/$clientId'
    | '/trainer/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/routines/$routineId'
    | '/routines/logs'
    | '/trainer/dashboard'
    | '/workouts/new'
    | '/workouts/prs'
    | '/exercises'
    | '/routines'
    | '/subscriptions'
    | '/workouts'
    | '/exercises/$exerciseId/history'
    | '/trainer/clients/$clientId'
    | '/trainer/clients'
  id:
    | '__root__'
    | '/routines/$routineId'
    | '/routines/logs'
    | '/trainer/clients'
    | '/trainer/dashboard'
    | '/workouts/new'
    | '/workouts/prs'
    | '/exercises/'
    | '/routines/'
    | '/subscriptions/'
    | '/workouts/'
    | '/exercises/$exerciseId/history'
    | '/trainer/clients/$clientId'
    | '/trainer/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RoutinesRoutineIdRoute: typeof RoutinesRoutineIdRoute
  RoutinesLogsRoute: typeof RoutinesLogsRoute
  TrainerClientsRoute: typeof TrainerClientsRouteWithChildren
  TrainerDashboardRoute: typeof TrainerDashboardRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  WorkoutsPrsRoute: typeof WorkoutsPrsRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  RoutinesIndexRoute: typeof RoutinesIndexRoute
  SubscriptionsIndexRoute: typeof SubscriptionsIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  ExercisesExerciseIdHistoryRoute: typeof ExercisesExerciseIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions/': {
      id: '/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/prs': {
      id: '/workouts/prs'
      path: '/workouts/prs'
      fullPath: '/workouts/prs'
      preLoaderRoute: typeof WorkoutsPrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/dashboard': {
      id: '/trainer/dashboard'
      path: '/trainer/dashboard'
      fullPath: '/trainer/dashboard'
      preLoaderRoute: typeof TrainerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/clients': {
      id: '/trainer/clients'
      path: '/trainer/clients'
      fullPath: '/trainer/clients'
      preLoaderRoute: typeof TrainerClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/logs': {
      id: '/routines/logs'
      path: '/routines/logs'
      fullPath: '/routines/logs'
      preLoaderRoute: typeof RoutinesLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/$routineId': {
      id: '/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof RoutinesRoutineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer/clients/': {
      id: '/trainer/clients/'
      path: '/'
      fullPath: '/trainer/clients/'
      preLoaderRoute: typeof TrainerClientsIndexRouteImport
      parentRoute: typeof TrainerClientsRoute
    }
    '/trainer/clients/$clientId': {
      id: '/trainer/clients/$clientId'
      path: '/$clientId'
      fullPath: '/trainer/clients/$clientId'
      preLoaderRoute: typeof TrainerClientsClientIdRouteImport
      parentRoute: typeof TrainerClientsRoute
    }
    '/exercises/$exerciseId/history': {
      id: '/exercises/$exerciseId/history'
      path: '/exercises/$exerciseId/history'
      fullPath: '/exercises/$exerciseId/history'
      preLoaderRoute: typeof ExercisesExerciseIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrainerClientsRouteChildren {
  TrainerClientsClientIdRoute: typeof TrainerClientsClientIdRoute
  TrainerClientsIndexRoute: typeof TrainerClientsIndexRoute
}

const TrainerClientsRouteChildren: TrainerClientsRouteChildren = {
  TrainerClientsClientIdRoute: TrainerClientsClientIdRoute,
  TrainerClientsIndexRoute: TrainerClientsIndexRoute,
}

const TrainerClientsRouteWithChildren = TrainerClientsRoute._addFileChildren(
  TrainerClientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  RoutinesRoutineIdRoute: RoutinesRoutineIdRoute,
  RoutinesLogsRoute: RoutinesLogsRoute,
  TrainerClientsRoute: TrainerClientsRouteWithChildren,
  TrainerDashboardRoute: TrainerDashboardRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  WorkoutsPrsRoute: WorkoutsPrsRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  RoutinesIndexRoute: RoutinesIndexRoute,
  SubscriptionsIndexRoute: SubscriptionsIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  ExercisesExerciseIdHistoryRoute: ExercisesExerciseIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
